// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvycmpxidewqoucmxbtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2eWNtcHhpZGV3cW91Y214YnRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MTkzNjEsImV4cCI6MjA2MzA5NTM2MX0.1wmf6WTBXTHEyDHcWdlnORFGCRSjcZ13bScxzSQCVps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);